### ISSUE TITLE
Hieroglyphics in waybar

### ISSUE THREAD

**Issue by git58** [jorgeloopzz/dotfiles#3]
In your screenshots I see icons in waybar for sway config. I clone your repo, and see weird symbols instead of some icons. When I add CJK font to waybar css config, I see chinese hieroglyphics instead of weird symbols.
![изображение](https://github.com/jorgeloopzz/dotfiles/assets/60933545/b5c4ddb3-76af-4003-bdf2-3d4ef21fe947)

**Comment by jorgeloopzz** [comment]
Hi mate. Firstly, sorry for the wait. Secondly, in order to have those symbols, it's necessary to add [Nerd Fonts](https://www.nerdfonts.com/), not any other type of font. Nerd Fonts are specific fonts for coding with glyphs and icons included as you see in my DE. In my case I use [Cousine  Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Cousine.zip) but you can use any other Nerd Font you like. To install, extract the zip, and move all the `.otf` or `.ttf` files  in `/usr/share/fonts`. Hope I could've helped!!

**Comment by git58** [comment]
I already installed Nerd Fonts, set Cousine Nerd Font and still have this issue(

**Comment by jorgeloopzz** [comment]
Where do you set the font? It must be in the [style.css](https://github.com/jorgeloopzz/dotfiles/blob/master/.config/waybar/style.css#L3) file and it has to be the exact name of the font. In case you wanna know the fonts you have installed run `fc-list : family | grep Nerd | sort | awk '{print $1 $2 $3}' | uniq`

**Comment by jorgeloopzz** [comment]
Recently working on my dotfiles, I realised to have the same problem. That's because glypsh have been updated, those I have don't work anymore. Just fixed my configs.
